app/controllers/bookings_controller.rb
app/models/booking.rb
app/views/bookings/create.html.erb
test/controllers/bookings_controller_test.rb

**Validations**
Added validations for presence from table
**Create method/action**
Added create action for booking

added validations, create action to booking

---

app/controllers/scooters_controller.rb
app/models/scooter.rb
app/views/scooters/create.html.erb
app/views/scooters/index.html.erb
app/views/scooters/new.html.erb
app/views/scooters/show.html.erb
config/routes.rb
test/controllers/scooters_controller_test.rb

**_finished with the scooter.rb models(validation) and finished with the scooter controllers(index, show, create and new_**

models & controllers

---

app/controllers/bookings_controller.rb
app/models/booking.rb
app/views/bookings/_form.html.erb
app/views/bookings/create.html.erb
config/routes.rb

Moved booking resource(s) to be nested under scooter

changed routing, commented everything of booking

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_index.scss
app/controllers/scooters_controller.rb
app/views/pages/home.html.erb
app/views/scooters/index.html.erb
app/views/shared/_navbar.html.erb

Search bar in landing page now works -> to redirect to scooters#index page

implemented search function and created scooters#index page

---

app/assets/stylesheets/components/_banner.scss

edited placeholder text color and position

editted searchbar

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_map.scss
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_show.scss
app/controllers/bookings_controller.rb
app/controllers/scooters_controller.rb
app/models/booking.rb
app/models/scooter.rb
app/views/bookings/_form.html.erb
app/views/bookings/index.html.erb
app/views/scooters/_form.html.erb
app/views/scooters/show.html.erb
app/views/shared/_navbar.html.erb
config/routes.rb
db/migrate/20190528054234_remove_price_from_bookings.rb
db/migrate/20190528054242_add_price_to_scooters.rb
db/migrate/20190528063438_remove_status_from_bookings.rb
db/schema.rb

**Table changes**
1. Removed price from booking, added it to scooter
2. Removed status from booking, added it to scooter
**Route**
1. Made an independent bookings#index route
**Design**
1. Created bookings form and bookings#index

Table, routes, booking design

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/pages/_edit.scss
app/assets/stylesheets/pages/_index.scss
app/controllers/bookings_controller.rb
app/views/bookings/_form.html.erb
app/views/bookings/edit.html.erb
app/views/bookings/index.html.erb
config/routes.rb

implemented edit method for booking and stylized scooter#index

---

db/migrate/20190527070419_create_scooters.rb
db/migrate/20190529055033_add_status_to_bookings.rb
db/schema.rb

1. Added status column to Booking with a default value
2. Added default value of scooter status column to 'Available'

added status to booking and added default value to scooter status column

---

Gemfile
Gemfile.lock
app/assets/stylesheets/components/_form.scss
app/assets/stylesheets/pages/_home.scss
app/controllers/application_controller.rb
app/controllers/bookings_controller.rb
app/controllers/reviews_controller.rb
app/controllers/scooters_controller.rb
app/policies/application_policy.rb
app/policies/booking_policy.rb
app/policies/review_policy.rb
app/policies/scooter_policy.rb
app/views/bookings/show.html.erb
app/views/reviews/_form.html.erb
app/views/scooters/index.html.erb
app/views/scooters/show.html.erb
test/policies/booking_policy_test.rb
test/policies/review_policy_test.rb
test/policies/scooter_policy_test.rb

implemented pundit on scooter, booking, and review

---

app/views/scooters/index.html.erb
app/views/shared/_footer.html.erb

moved add scooter button

---

app/assets/stylesheets/components/_form.scss
app/assets/stylesheets/pages/_show.scss
app/controllers/users_controller.rb
app/policies/user_policy.rb
app/views/shared/_navbar.html.erb
app/views/users/show.html.erb
config/routes.rb
test/controllers/users_controller_test.rb
test/policies/user_policy_test.rb

Added profile page along with policies for user

added profile page and profile policy

---

app/assets/stylesheets/pages/_new.scss
app/javascript/packs/application.js
app/views/bookings/index.html.erb
app/views/devise/sessions/new.html.erb
app/views/reviews/_form.html.erb
app/views/scooters/show.html.erb

Dynamic total price and days on booking form (scooter#show page)

implemented dynamic total price on booking form

---

app/assets/stylesheets/pages/_show.scss
app/views/bookings/index.html.erb

changed text on booking index buttons

---

app/assets/stylesheets/pages/_edit.scss
app/assets/stylesheets/pages/_new.scss
app/assets/stylesheets/pages/_show.scss
app/models/user.rb
app/views/bookings/index.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/shared/_links.html.erb
app/views/users/show.html.erb

**Bookings#index**
1. Total price shown
2. Days shown
**User**
1. Added destroy dependencies
**Styling**
1. Added styling to forgot password page

added total price and days in bookings#index, added destroy dependencies

---

app/views/scooters/show.html.erb

**Reviews**
Added reviewer name to reviews (closed issue #74 )

added reviewer

---

Gemfile
Gemfile.lock
app/assets/stylesheets/components/_map.scss
app/assets/stylesheets/pages/_show.scss
app/controllers/scooters_controller.rb
app/javascript/components/booking.js
app/javascript/packs/application.js
app/javascript/plugins/init_autocomplete.js
app/javascript/plugins/init_mapbox.js
app/javascript/plugins/init_mapbox_all.js
app/models/scooter.rb
app/views/layouts/application.html.erb
app/views/scooters/_form.html.erb
app/views/scooters/_infowindow.html.erb
app/views/scooters/index.html.erb
app/views/scooters/show.html.erb
config/initializers/geocoder.rb
db/migrate/20190530031932_add_coordinates_to_scooters.rb
db/schema.rb
package.json
yarn.lock

**Scooter**
1. Added mapbox and algolia plugin
2. Made a map on scooters#show and scooters#index
3. Each scooter has a lat&lng which is shown as a pin in the map

Scooter changes

---

app/assets/stylesheets/pages/_show.scss
app/views/bookings/index.html.erb
app/views/scooters/index.html.erb
db/schema.rb

We don't really need scroll-behaviour anymore.

delete scroll-behavior: smooth; on show.css

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_index.scss
app/controllers/scooters_controller.rb
app/models/scooter.rb
app/policies/scooter_policy.rb
app/views/devise/registrations/new.html.erb
app/views/devise/shared/_links.html.erb
app/views/scooters/index.html.erb
app/views/scooters/show.html.erb
config/routes.rb

*Delete*
implemented delete method in scooters controller, also pundit includet 
*also*
fixed parts of the login and sing up sass

added destroy method to scooter

---

app/views/devise/passwords/new.html.erb

Removed double links to log in and sign up. Add button for link

reset password page changed. 

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_infowindow.scss
app/controllers/scooters_controller.rb
app/javascript/components/booking.js
app/javascript/packs/application.js
app/javascript/plugins/init_mapbox.js
app/javascript/plugins/init_mapbox_all.js
app/views/scooters/_indexinfowindow.html.erb
app/views/scooters/_infowindow.html.erb
app/views/scooters/index.html.erb

Fixed info window on scooters#index

fixed index info window

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_map.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_home.scss
app/javascript/plugins/init_mapbox_all.js
app/views/scooters/index.html.erb
app/views/shared/_navbar.html.erb

Map position fixed

---

app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/pages/_show.scss
app/views/scooters/show.html.erb

Closed issue #37 
'Back to list' button now sticky to screen on top left

fixed button location

---

app/models/booking.rb
app/views/bookings/index.html.erb

**Upon booking**
1. Scooter's status changes to 'Unavailable'
**Upon cancelling booking**
1. Scooter's status changes back to 'Available'

scooter status changes

---

app/views/shared/_navbar.html.erb

Navbar inconsistent (following user on the show page) -> now fixed

fix avatar navbar
